### ISSUE TITLE
为什么不生效了？

### ISSUE THREAD

**Issue by CrazyTaobean** [2293736867/JetBrainsActivation#1]

**Comment by 2293736867** [comment]
哪一个IDE，什么版本的，可以尝试一下删除用户目录下的对应的数据文件夹再重新激活。

**Comment by CrazyTaobean** [comment]
最新版的Clion，之前用的idea和pycharm都激活成功了，今天这个怎么都无法激活，重启idea后还需要重新激活。。实在不知道怎么回事

**Comment by 2293736867** [comment]
尝试删除一下用户数据文件，[参考](https://blog.csdn.net/qq_27525611/article/details/106409501)

**Comment by CrazyTaobean** [comment]
把文件全都删掉吗？

**Comment by CrazyTaobean** [comment]
清空了还是不行，是不是我的版本太新了啊

**Comment by CrazyTaobean** [comment]
我下载一个1.1版本试一下，应该不用断网吧？

**Comment by 2293736867** [comment]
可能是版本的原因
试一下1.1
