### ISSUE TITLE
Which versions of jetbrains products are supported in this latest version that you sent 5 days ago?

### ISSUE THREAD

**Issue by dan-developer** [2293736867/JetBrainsActivation#3]
Which versions of jetbrains products are supported in this latest version that you sent 5 days ago?

**Comment by 2293736867** [comment]
Hello, 2020.2 is supported, including IDEA 2020.2, PyCharm 2020.2, WebStorm 2020.2.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "2293736867/JetBrainsActivation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上6:17
收件人:&nbsp;"2293736867/JetBrainsActivation"<JetBrainsActivation@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[2293736867/JetBrainsActivation] Which versions of jetbrains products are supported in this latest version that you sent 5 days ago? (#3)





 
Which versions of jetbrains products are supported in this latest version that you sent 5 days ago?

**Comment by dan-developer** [comment]
Tested in PyCharm, WebStorm and PHPStorm. Thank you.
