### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by chenchuhaocharlie** [2293736867/JetBrainsActivation#4]
具体支持到2020.2.几呢？目前在用2020.1.3。

**Comment by 2293736867** [comment]
2020.10.09测试，IDEA最新版2020.2.3可行。

**Comment by chenchuhaocharlie** [comment]
谢谢！


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: bingling <notifications@github.com>
发送时间: Friday, October 9, 2020 12:18:29 AM
收件人: 2293736867/JetBrainsActivation <JetBrainsActivation@noreply.github.com>
抄送: 陈楚皓 <chenchuhaocharlie@outlook.com>; Author <author@noreply.github.com>
主题: Re: [2293736867/JetBrainsActivation] 一个问题 (#4)


Closed #4<https://github.com/2293736867/JetBrainsActivation/issues/4>.

―
