### ISSUE TITLE
Argument Code is not accepting.

### ISSUE THREAD

**Issue by soniumeshg** [2293736867/JetBrainsActivation#7]
Hello,

I used the below argument code but it is not accepting. Can you please check it willl be great support.

**HbVMaxqQrTt4UvDUk8fhyFT7uRdv48bqJsQMwVFp53YH9PZC9l+ZxAgnA60cLwwhURw/e4DcZZtle4tQzur4yWRk35qghES4JLFlmKty/UNiYh6RZIKxeCNPTCvYXflmKty/UNiYh6RZyXflmKty/UNiYh6RZyXeCNPTC201**

After pasting when i click on install for WebStrom it is not activating still same window is opened.

Regards,
Umesh Soni

**Comment by 2293736867** [comment]
Hello,

Do you use the agrument code metioned on the `README.md`？

The complete code is:
```bash
HbVMaxqQrTt4UvDUk8fhyFT7uRdv48bqJsQMwVFp53YH9PZC9l+ZxAgnA60cLwwhURw/e4DcZZtle4tQzur4yWRk35qghES4JLFlmKty/UNiYh6RZyXeCNPTCvIqxT9HR2YKqQT93be6AfLTcbJwPSLO201g+HbMbg6+aK1MUJI
```
Instead of your argument code:
```bash
HbVMaxqQrTt4UvDUk8fhyFT7uRdv48bqJsQMwVFp53YH9PZC9l+ZxAgnA60cLwwhURw/e4DcZZtle4tQzur4yWRk35qghES4JLFlmKty/UNiYh6RZIKxeCNPTCvYXflmKty/UNiYh6RZyXflmKty/UNiYh6RZyXeCNPTC201
```
